-- AutoERP Pro — Supabase jadvallarining NUMERIC precision'ini kengaytirish
-- Bu SQL ni Supabase Dashboard -> SQL Editor da ishga tushiring

-- SUPPLIERS
ALTER TABLE suppliers ALTER COLUMN debt TYPE NUMERIC(20, 2);

-- CUSTOMERS
ALTER TABLE customers ALTER COLUMN total_purchases TYPE NUMERIC(20, 2);
ALTER TABLE customers ALTER COLUMN debt TYPE NUMERIC(20, 2);

-- PRODUCTS
ALTER TABLE products ALTER COLUMN buy_price TYPE NUMERIC(20, 2);
ALTER TABLE products ALTER COLUMN sell_price TYPE NUMERIC(20, 2);
ALTER TABLE products ALTER COLUMN quantity TYPE NUMERIC(15, 2);
ALTER TABLE products ALTER COLUMN min_qty TYPE NUMERIC(15, 2);

-- EMPLOYEES
ALTER TABLE employees ALTER COLUMN salary TYPE NUMERIC(20, 2);
ALTER TABLE employees ALTER COLUMN advance TYPE NUMERIC(20, 2);

-- EXPENSES
ALTER TABLE expenses ALTER COLUMN amount TYPE NUMERIC(20, 2);

-- INCOMING
ALTER TABLE incoming ALTER COLUMN qty TYPE NUMERIC(15, 2);
ALTER TABLE incoming ALTER COLUMN buy_price TYPE NUMERIC(20, 2);

-- SALES
ALTER TABLE sales ALTER COLUMN discount TYPE NUMERIC(20, 2);
ALTER TABLE sales ALTER COLUMN total TYPE NUMERIC(20, 2);
ALTER TABLE sales ALTER COLUMN profit TYPE NUMERIC(20, 2);

-- SALE_ITEMS
ALTER TABLE sale_items ALTER COLUMN qty TYPE NUMERIC(15, 2);
ALTER TABLE sale_items ALTER COLUMN price TYPE NUMERIC(20, 2);
ALTER TABLE sale_items ALTER COLUMN buy_price TYPE NUMERIC(20, 2);

-- DEBT_PAYMENTS
ALTER TABLE debt_payments ALTER COLUMN amount TYPE NUMERIC(20, 2);
    