/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppIncomingRouteImport } from './routes/_app.incoming'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDebtsRouteImport } from './routes/_app.debts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppBarcodeRouteImport } from './routes/_app.barcode'
import { Route as AppAuditRouteImport } from './routes/_app.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomingRoute = AppIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBarcodeRoute = AppBarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/barcode': typeof AppBarcodeRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/incoming': typeof AppIncomingRoute
  '/inventory': typeof AppInventoryRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/barcode': typeof AppBarcodeRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/employees': typeof AppEmployeesRoute
  '/expenses': typeof AppExpensesRoute
  '/incoming': typeof AppIncomingRoute
  '/inventory': typeof AppInventoryRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/barcode': typeof AppBarcodeRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/incoming': typeof AppIncomingRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/barcode'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/employees'
    | '/expenses'
    | '/incoming'
    | '/inventory'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/barcode'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/debts'
    | '/employees'
    | '/expenses'
    | '/incoming'
    | '/inventory'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/barcode'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/debts'
    | '/_app/employees'
    | '/_app/expenses'
    | '/_app/incoming'
    | '/_app/inventory'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incoming': {
      id: '/_app/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof AppIncomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barcode': {
      id: '/_app/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof AppBarcodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBarcodeRoute: typeof AppBarcodeRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppIncomingRoute: typeof AppIncomingRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBarcodeRoute: AppBarcodeRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppIncomingRoute: AppIncomingRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
